sudo: required

dist: bionic

language: python

python:

  - "3.8"

before_install:

  - wget -nv https://download.opensuse.org/repositories/home:liberouter/xUbuntu_18.04/Release.key -O Release.key

  - sudo apt-key add - < Release.key

  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/liberouter/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/libyang.list"

  - sudo apt-get update

  - sudo apt-get install --allow-unauthenticated libyang

install: 

   - pip install pyang
   - pip install xym
   - pip install xml2rfc

script:

  - cd I-D-L2NM
  - xym draft-barguil-opsawg-l2sm-l2nm-01.txt
  - export yang_extracted=`ls *.yang`
  - diff $yang_extracted ../Yang/ietf-l2vpn-ntw.yang
  - xml2rfc draft-barguil-opsawg-l2sm-l2nm-02.xml
  - cd ..
  - cd Yang
  - pyang -f tree --ietf ietf-l2vpn-ntw.yang
  - yanglint -f yang ietf-l2vpn-ntw.yang

 
